### PR TITLE
added ROT13 and some lab from session 3

### PR DESCRIPTION
**Pull request by gaffneyt**

### CODE REVIEW

**Comment by summerela** [comment]
FizzBuzz looks great! 

ROT13: your assert statement needs to be == (A single = sign is used to assign a value, as in pie = 'good', and == is used to test equality conditions, as in 'assert a == b') 

mailroom: While testing sendathankyou(), after the letter prints, I get a message asking for the donation amount again, and then the function breaks; I recommend writing out the steps in pseudocode as comments, and then filling in the actual code following your comments, just so that you can keep everything flowing in the right direction. For example, why do you have the break statement where you do? 

printareport() looks good. 

while(True):
        userinput = input('Welcome to the mailroom!  Would you like to :\n    \1. Send a Thank you  \n    2. Create a report  \n    3.  Quit \nChoice 1, 2 or 3?:')
        if (userinput == str(1)): <--- why are you casting your int to a string here? 

Mailroom is under way, you're off to a good start. Email me if you get stuck!

**Comment by summerela** [comment]
Oops, just saw your mailroomfinal.py. I was looking at your interim mailroom assignment :+1:

**Comment by gaffneyt** [comment]
Thanks Summer!  Does the final look ok?

**Comment by summerela** [comment]
I'm planning to do some grading Wednesday night, so I'll let you know then!

On Sun, Feb 7, 2016 at 11:54 AM, gaffneyt <notifications@github.com> wrote:

> Thanks Summer! Does the final look ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/UWPCE-PythonCert/IntroPython2016a/pull/42#issuecomment-181094139>
> .
>



-- 
Thanks,
Summer Rae
summerrae78@gmail.com

**Comment by gaffneyt** [comment]
TY, I'll try and get the udpates from this week in there by then as well.

Appreciate the help!

**Comment by summerela** [comment]
Yep, looks great! Nicely done!

**Comment by summerela** [comment]
@rriehle There are some conflicts with this merge that I do not feel comfortable accepting. Can you please take a look when you get a chance? Thanks!

**Pull request closed without merging**
